### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DissenterNet** [Qortal/qortal-ui#164]
Not sure if this is the place for this but there is a typo on the Publish/Update Qapp page. ",so that it can more easily accessed by peers" is probably meant to say  "more easily be accessed".

Oh and following the link bellow submit new issue their is a hyperlink to contribution guidelines and I checked it out and there is a typo there as well. 
"As long the code change is good"
probably to "As long as the code change is good".
Thanks and keep up the great work.

**Comment by AlphaX-Projects** [comment]
@DissenterNet as i can see that you have an github account, feel free to make a PR.
Whne you don't want just let me know then i correct it.

**Comment by DissenterNet** [comment]
Im very new to github. When I learn how to do that I would be happy to. Thanks

**Comment by fyrak1s** [comment]
@DissenterNet 
>Im very new to github. When I learn how to do that I would be happy to. Thanks

The most "difficult" part would be to find the corresponding string (string = text) in the project and modify it. Unless your are already familiar with the source code structure of the project that is not possible through the web UI of GitHub afaik.

I have now made a PR for that change (see #166 / https://github.com/Qortal/qortal-ui/pull/166/commits/7f9762ae826ccb3a0869d5d7d025a53707497c17), my steps have been:
1. Fork the project (via github UI)
2. Clone it to my local system via command line `git clone <url_of_fork>`
3. Open the project folder with VSCode
4. Search for the string "so that it can more easily accessed by peers"
5. Edit the file ([core/language/us.json](https://github.com/Qortal/qortal-ui/blob/master/core/language/us.json#L579) in our case)
6. Add changed file to stages changes `git add core/language/us.json`
7. Commit changes with a commit message `git commit -m "Update us.json"`
8. Push changes to your fork on GitHub `git push origin master`
9. Then make PR via GitHub UI (merge your fork with original project)

If you had known which file to edit in the first place, you could have also done it all via GitHub web interface like this:
1. Go to [core/language/us.json](https://github.com/Qortal/qortal-ui/blob/master/core/language/us.json#L579)
2. Click "Edit" (Pen icon)
3. Make the text change and save changes, it will automatically create a fork (basically a copy of the project under your profile)
4. Then go to https://github.com/Qortal/qortal-ui/pulls and select "New Pull Request"
5. Select your change and Submit PR
